#ifndef MINESWEEPER_CONFIG_H
#define MINESWEEPER_CONFIG_H

#define BEGINNER_FIELD_HEIGHT 9
#define BEGINNER_FIELD_WIDTH 9

#define INTERMEDIATE_FIELD_HEIGHT 16
#define INTERMEDIATE_FIELD_WIDTH 16

#define ADVANCED_FIELD_HEIGHT 16
#define ADVANCED_FIELD_WIDTH 30

#endif // MINESWEEPER_CONFIG_H
